modLoader = "javafml"
loaderVersion = "[${forge_major_ver},)"
license = "MIT License"
issueTrackerURL = "https://github.com/aksource/AkLib/issues"
displayURL = "https://github.com/aksource/AkLib/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "ak"
[[mods]]
modId = "ak_lib"
version = "${file.jarVersion}"
displayName = "AKLib"
updateJSONURL="https://raw.githubusercontent.com/aksource/AKLib/main/update.json"
description = '''

    '''
[[dependencies.ak_lib]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ak_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
