modLoader = "javafml" #mandatory
loaderVersion = "[41,)" #mandatory (24 is current forge version)
license = "MIT License"
issueTrackerURL = "https://github.com/aksource/AkLib/issues" #optional
displayURL = "https://github.com/aksource/AkLib/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "ak" #optional
[[mods]] #mandatory
modId = "ak_lib" #mandatory
version = "1.19-1.0.3.0" #mandatory
displayName = "AKLib" #mandatory
#updateJSONURL="http://myurl.me/" #optional
description = '''

    '''
[[dependencies.ak_lib]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ak_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
